### ISSUE TITLE
Extend functionality for whole day data

### ISSUE THREAD

**Issue by luxa110** [grinco/ote_rate#10]
Hi, at first thanks a lot for this development.
Q: Is it possible to extend functionality to read and expose all day data means for each hour (and in best scenario also for next day)?
Thanks once again.

**Comment by grinco** [comment]
It's already there - in the attributes. See attached.
![Screenshot_2023-02-21-21-38-15-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/5553528/220453119-f955dc7c-74b3-4044-9187-eb8805a8f7b4.jpg)
