### ISSUE TITLE
hourly price shift

### ISSUE THREAD

**Issue by czechdude** [grinco/ote_rate#12]
Ahoj, dobrá práce s pluginem, díky!
Mám dotaz na hodinové sazby. Pokud jsou na OTE vylistované v tabulce sloupce 1-24, platí ty ceny pro 00:00-00:59 pro první soupec atd až 23:00-23:59 pro 24. sloupec? 
Hassio mi ukazuje cenu např teď pro předchozí hodinu.
Jak je to správně?
Díky!

![image](https://user-images.githubusercontent.com/601761/221188708-8b7a1e39-32ba-459f-b9c7-8d80739f1031.png)

vs

![image](https://user-images.githubusercontent.com/601761/221188848-10e98484-976d-4343-93c2-b044e979c1a7.png)

**Comment by grinco** [comment]
The hour index in home assistant is the hour for which the price is valid. 0 = 00:XX, 15 = 15:XX, etc.
Line 13 in the integration = line 14 on your screenshot (they start counting from 1).

**Comment by czechdude** [comment]
Well, I still think it is wrong, because the price in the OTE graph shows
prices for prices over the day from 00:00 to 23:59 and the first row shows
price from 00:00-00:59 and has hour value 1 in the OTE table. => HA shows
the current price for the PREVIOUS hour, from what I can read from the
graph. The index of the attributes in the table in HA is OK.

pá 24. 2. 2023 v 18:28 odesílatel grinco ***@***.***> napsal:
