### ISSUE TITLE
different calculation / odlišný výpočet

### ISSUE THREAD

**Issue by valentapat** [grinco/ote_rate#13]
Zdravim a jen chci demonstrovat rozdil vypoctene ceny mnou a Vami (home-assistantem) a to na celkem male castce, 
ceny ote-cr nam sedi, spotrba temer taky a distribuci tam pocitam zvlast.  Ja na to pouzivam hjodnoty watthodin dodavane stridacem, myslim ze vy uz tam mate ze senzoru zaokrouhlene kWh, zaokrouhleni delam az na konci - asi bude rozdil tady co ?

Zatim nemam, ale az bude vyuctovani dodavatele, prilozim to sem

pekny den p.v.

![Obrázek WhatsApp, 2023-05-12 v 06 23 30](https://github.com/grinco/ote_rate/assets/17265945/2708b25e-9670-40e0-836d-6c9f677f4ed1)

![Obrázek WhatsApp, 2023-05-12 v 06 23 31](https://github.com/grinco/ote_rate/assets/17265945/63d8b348-30ef-4109-b4ec-c3f2f61562cd)

**Comment by grinco** [comment]
The cost is only informational. I am assuming that you don't have a realtime meter, and your energy provider calculates your consumption based on some averages through the country. We display realtime data from OTE portal - everything else is irrelevant for this integation.
