### ISSUE TITLE
Unable to add repository

### ISSUE THREAD

**Issue by svecpetr** [grinco/ote_rate#4]
I am unable to add repostory for OTE Rate

![obrazek](https://user-images.githubusercontent.com/10357663/203401179-b7965947-1509-45b8-ab54-bd7fd5c143f5.png)

Home Assistant 2022.11.4 
Supervisor 2022.10.2 
Operating System 9.3 
Frontend 20221108.0 - latest 

Where is the problem?

**Comment by grinco** [comment]
It's a HACS, not hassid addon.
