### ISSUE TITLE
Outdated installation information

### ISSUE THREAD

**Issue by svecpetr** [grinco/ote_rate#5]
Outdated information about instalation at this pages...

Definitely is not possible to add sensor configuration to configuration.yaml

![obrazek](https://user-images.githubusercontent.com/10357663/203404281-c81ed058-6a1f-4d72-9a70-ccf01d0f12da.png)

 Home Assistant 2022.11.4
 Supervisor 2022.10.2
 Operating System 9.3
 Frontend 20221108.0 - latest

**Comment by radovole** [comment]
try this:

 - platform: ote_rate

... yout forgot "-"

**Comment by grinco** [comment]
Fixed
